#!/usr/bin/env python3
"""Batch-5 tables, numbers and figure (held-out weather, update-rate sweep, baselines at epoch 50).

    python aamas2027/scripts/make_batch5.py

Reads every finished run (status ok, provenance match) from aamas2027/runs and
aamas2027/batch*_runs/*/runs. Writes, in aamas2027/paper/:
  tab_weather.tex      RBC vs our agent per climate (training climate + held-out)
  tab_rate_sweep.tex   state-independent selectors at 1x/2x/4x the learned rate and at the RBC's rate
  fig_rate_sweep.pdf   violations and electricity against update rate
  numbers_batch5.tex   macros used in the text
  batch5_summary.json
Missing runs appear as red TBD.
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

import numpy as np

HERE = Path(os.path.abspath(__file__)).parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "sdar_eval"))
import kpis as K  # noqa: E402
import make_baselines as MB  # noqa: E402  (finished_runs, load)

AAMAS = HERE.parent
ROOT = AAMAS.parent
OUT = AAMAS / "paper"
RBC_SF = ROOT / "offline_smooth_clean_episode_000.csv"
COLS = [("combined_kwh_day", 1), ("tv_pct", 1), ("dzh_day", 2), ("vis_in_pct", 1), ("upd_pct", 1)]


def f(v, nd=1):
    return r"\textcolor{red}{TBD}" if v is None or not np.isfinite(v) else f"{v:.{nd}f}"


def camel(tag):
    return "".join(p.capitalize() for p in re.split(r"[^A-Za-z]+", tag) if p)


_CACHE = {}


def load(path):
    path = Path(path)
    if path not in _CACHE:
        if path.suffix == ".npz":
            ann, day = MB.load(path)
        else:
            df = K.load(path)
            ann, day = K.annual(df), K.daily(df)
        _CACHE[path] = (ann, day)
    return _CACHE[path]


def mean_runs(paths):
    if not paths:
        return None, None
    anns, days = zip(*(load(p) for p in paths))
    agg = {c: float(np.mean([a[c] for a in anns if a.get(c) is not None])) for c, _ in COLS if any(a.get(c) is not None for a in anns)}
    agg.update({c + "_sd": float(np.std([a[c] for a in anns], ddof=1)) if len(anns) > 1 else None for c, _ in COLS if c in agg})
    agg["n"] = len(paths)
    day = np.nanmean([d[["combined_kwh", "tv_pct", "dzh"]].to_numpy(float) for d in days], axis=0)
    return agg, day


def paired(day_a, day_b):
    if day_a is None or day_b is None:
        return None
    return {k: K.block_bootstrap_mean(day_a[:, i] - day_b[:, i], block=30)
            for i, k in enumerate(("combined_kwh", "tv_pct", "dzh"))}


def main():
    runs = MB.finished_runs()                       # name -> rollout path (csv or npz)

    def pick(pattern):
        return [p for n, p in sorted(runs.items()) if re.match(pattern, n)]

    res = {"weather": {}, "rates": {}, "baselines_e50": {}}
    L = ["% generated by make_batch5.py; do not edit"]

    # ---------------- A: weather ----------------
    rbc_sf, rbc_sf_day = mean_runs([RBC_SF])
    ours_sf, ours_sf_day = mean_runs(pick(r"^b3e100_sample_s\d+$"))
    climates = [("sf", "SF (training)", rbc_sf, rbc_sf_day, ours_sf, ours_sf_day, None)]
    retuned = {}   # tag -> (annual, daily) of the RBC with the 22-25 C band (rbc_b2225_<tag>)
    tags = sorted({m.group(1) for n in runs for m in [re.match(r"^rbc_clean_(\w+)$", n)] if m and m.group(1) != "sf"}
                  | {m.group(1) for n in runs for m in [re.match(r"^b3e100_([a-z_]+)_sample_s\d+$", n)] if m})
    for tag in ["sf"] + tags:
        retuned[tag] = mean_runs(pick(rf"^rbc_b2225_{tag}$"))
    for tag in tags:
        r, rd = mean_runs(pick(rf"^rbc_clean_{tag}$"))
        o, od = mean_runs(pick(rf"^b3e100_{tag}_sample_s\d+$"))
        tss = sorted({int(m.group(1)) for n in runs for m in [re.match(rf"^sdar_iql_t(\d+)_e100_{tag}_sample_s\d+$", n)] if m})
        tr = {ts: mean_runs(pick(rf"^sdar_iql_t{ts}_e100_{tag}_sample_s\d+$"))[0] for ts in tss}
        climates.append((tag, tag.replace("_", " ").title(), r, rd, o, od, tr))
    repro = mean_runs(pick(r"^rbc_clean_sf$"))[0]
    if repro:
        res["rbc_sf_reproduction"] = {c: [repro.get(c), rbc_sf.get(c)] for c, _ in COLS}
        L.append(f"\\newcommand{{\\RbcReproE}}{{{f(repro['combined_kwh_day'])}}}")
        L.append(f"\\newcommand{{\\RbcReproTv}}{{{f(repro['tv_pct'], 2)}}}")

    T = [r"\begin{table}[t]",
         r"\caption{Rule-based controllers and a held-out climate. San Francisco (SF) is the training climate; Fresno was "
         r"used neither for data collection, training nor reward design, and all controllers run unchanged there "
         r"(only the weather file differs). "
         r"Data RBC: the controller that generated the dataset (idle band 21--24\,$^\circ$C); retuned RBC: the same controller with its idle band moved to 22--25\,$^\circ$C. "
         r"Ours: mean over selector seeds of the reported checkpoint. Paired differences with 95\% intervals are given in the text.}",
         r"\label{tab:weather}", r"\small", r"\setlength{\tabcolsep}{4pt}",
         r"\begin{tabular*}{\columnwidth}{@{\extracolsep{\fill}}llrrrrr@{}}", r"\toprule",
         r"Climate & Controller & kWh/d & Viol.\,\% & Kzh/d & Vis.\,\% & Upd.\,\% \\", r"\midrule"]
    for tag, label, r, rd, o, od, tr in climates:
        d = paired(od, rd)
        r2, rd2 = retuned.get(tag, (None, None))
        d2 = paired(od, rd2)
        res["weather"][tag] = {"label": label, "rbc": r, "ours": o, "paired_ours_minus_rbc": d,
                               "training_seeds": tr, "rbc_band22_25": r2, "paired_ours_minus_rbc_band22_25": d2}
        cell = "--"
        if d:
            (m, lo, hi), (mt, lot, hit) = d["combined_kwh"], d["tv_pct"]
            cell = f"{m:+.1f} [{lo:+.1f}, {hi:+.1f}], {mt:+.1f} [{lot:+.1f}, {hit:+.1f}]"
        rows = [("Data RBC", r, "")]
        if r2:
            rows.append(("Retuned RBC", r2, ""))
        rows.append(("Ours", o, cell))
        for i, (ctl, a, c) in enumerate(rows):
            row = [label if i == 0 else "", ctl] + [f((a or {}).get(k), nd) for k, nd in COLS]
            T.append(" & ".join(row) + r" \\")
        T.append(r"\addlinespace" if tag != climates[-1][0] else r"\bottomrule")
        nm = "Sf" if tag == "sf" else camel(tag)
        for who, a in (("Rbc", r), ("RbcB", r2), ("Ours", o)):
            for k, tg, nd in (("combined_kwh_day", "E", 1), ("tv_pct", "Tv", 1), ("dzh_day", "Dzh", 2),
                              ("vis_in_pct", "Vis", 1), ("upd_pct", "Upd", 1)):
                L.append(f"\\newcommand{{\\Wx{nm}{who}{tg}}}{{{f((a or {}).get(k), nd)}}}")
        red = (100 * (1 - o["combined_kwh_day"] / r["combined_kwh_day"])) if (o and r) else None
        L.append(f"\\newcommand{{\\Wx{nm}RedE}}{{{f(red)}}}")
        for k, tg, nd in (("combined_kwh", "E", 1), ("tv_pct", "Tv", 1), ("dzh", "Dzh", 2)):
            for dd, pre in ((d, "Delta"), (d2, "DeltaB")):
                v = (dd or {}).get(k)
                L += [f"\\newcommand{{\\Wx{nm}{pre}{tg}{s}}}{{{f(v[i] if v else None, nd)}}}" for i, s in enumerate(("", "Lo", "Hi"))]
        redb = (100 * (1 - o["combined_kwh_day"] / r2["combined_kwh_day"])) if (o and r2) else None
        L.append(f"\\newcommand{{\\Wx{nm}RedBE}}{{{f(redb)}}}")
        if tr:
            words = {1: "One", 2: "Two", 3: "Three", 4: "Four", 5: "Five", 6: "Six"}
            for ts, a in tr.items():
                L.append(f"\\newcommand{{\\Wx{nm}T{words[ts]}E}}{{{f((a or {}).get('combined_kwh_day'))}}}")
                L.append(f"\\newcommand{{\\Wx{nm}T{words[ts]}Tv}}{{{f((a or {}).get('tv_pct'))}}}")
            # all training runs together: the reported checkpoint (mean over its selector seeds) + every extra run
            allr = [o] + [a for a in tr.values() if a]
            ev = [a["combined_kwh_day"] for a in allr if a]
            tv = [a["tv_pct"] for a in allr if a]
            L.append(f"\\newcommand{{\\Wx{nm}AllN}}{{{len(ev)}}}")
            for nmk, vals, nd in (("E", ev, 1), ("Tv", tv, 1)):
                L.append(f"\\newcommand{{\\Wx{nm}All{nmk}Mean}}{{{f(float(np.mean(vals)) if vals else None, nd)}}}")
                L.append(f"\\newcommand{{\\Wx{nm}All{nmk}Min}}{{{f(min(vals) if vals else None, nd)}}}")
                L.append(f"\\newcommand{{\\Wx{nm}All{nmk}Max}}{{{f(max(vals) if vals else None, nd)}}}")
            if r2 and tv:
                L.append(f"\\newcommand{{\\Wx{nm}AllTvAtMostRbcB}}{{{sum(1 for x in tv if x <= r2['tv_pct'])}}}")
            if r and tv:
                L.append(f"\\newcommand{{\\Wx{nm}AllTvBelowRbc}}{{{sum(1 for x in tv if x < r['tv_pct'])}}}")
            if r and ev:
                L.append(f"\\newcommand{{\\Wx{nm}AllEBelowRbc}}{{{sum(1 for x in ev if x < r['combined_kwh_day'])}}}")
            if r2 and ev:
                L.append(f"\\newcommand{{\\Wx{nm}AllEBelowRbcB}}{{{sum(1 for x in ev if x < r2['combined_kwh_day'])}}}")
    T += [r"\end{tabular*}", r"\end{table}"]
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "tab_weather.tex").write_text("\n".join(T) + "\n")

    # ---------------- B: update-rate sweep ----------------
    learned, _ = mean_runs(pick(r"^b3e100_sample_s\d+$"))
    groups = {"learned": learned, "always": mean_runs(pick(r"^b3e100_always$"))[0],
              "threshold": mean_runs(pick(r"^b3e100_threshold$"))[0],
              "clock": mean_runs(pick(r"^b3e100_clock_s\d+$"))[0]}     # batch 7: hour-of-day selector
    for sel in ("periodic", "constant"):
        groups[f"{sel}_x1"] = mean_runs(pick(rf"^b3e100_{sel}_s\d+$"))[0]
        for lab in ("x2", "x4", "rbcrate"):
            groups[f"{sel}_{lab}"] = mean_runs(pick(rf"^b3e100_{sel}_{lab}_s\d+$"))[0]
    res["rates"] = groups
    names = {"periodic": "Periodic", "constant": "Random"}
    labels = {"x1": r"$1\times$ learned", "x2": r"$2\times$ learned", "x4": r"$4\times$ learned", "rbcrate": "RBC rate"}
    T = [r"\begin{table}[t]",
         r"\caption{State-independent selectors at different update budgets (same checkpoint and proposals). "
         r"$k\times$ learned: $k$ times the learned per-subsystem update rates; RBC rate: the behaviour controller's own "
         r"per-subsystem rates. Means over selector seeds.}",
         r"\label{tab:rates}", r"\small", r"\setlength{\tabcolsep}{3pt}", r"\resizebox{\columnwidth}{!}{%",
         r"\begin{tabular}{@{}llrrrrr@{}}", r"\toprule",
         r"Selector & Budget & kWh/d & Viol.\,\% & Kzh/d & Vis.\,\% & Upd.\,\% \\", r"\midrule",
         "Learned (sampled) & -- & " + " & ".join(f((learned or {}).get(k), nd) for k, nd in COLS) + r" \\", r"\addlinespace"]
    for sel in ("periodic", "constant"):
        for lab in ("x1", "x2", "x4", "rbcrate"):
            a = groups.get(f"{sel}_{lab}") or {}
            T.append(f"{names[sel] if lab == 'x1' else ''} & {labels[lab]} & " + " & ".join(f(a.get(k), nd) for k, nd in COLS) + r" \\")
            nm = f"Rate{names[sel]}{ {'x1': 'One', 'x2': 'Two', 'x4': 'Four', 'rbcrate': 'Rbc'}[lab] }"
            for k, tg, nd in (("combined_kwh_day", "E", 1), ("tv_pct", "Tv", 1), ("upd_pct", "Upd", 1)):
                L.append(f"\\newcommand{{\\{nm}{tg}}}{{{f(a.get(k), nd)}}}")
        T.append(r"\addlinespace")
    if groups.get("clock"):
        a = groups["clock"]
        T += ["Time of day & $1\\times$ learned & " + " & ".join(f(a.get(k), nd) for k, nd in COLS) + r" \\", r"\addlinespace"]
    a = groups.get("always") or {}
    T += ["Always update & -- & " + " & ".join(f(a.get(k), nd) for k, nd in COLS) + r" \\",
          r"\bottomrule", r"\end{tabular}}", r"\end{table}"]
    (OUT / "tab_rate_sweep.tex").write_text("\n".join(T) + "\n")
    stat = [g for k, g in groups.items() if g and (k.startswith("periodic") or k.startswith("constant") or k in ("always", "clock"))]
    if stat:
        best = min(stat, key=lambda g: g["tv_pct"])
        L.append(f"\\newcommand{{\\RateBestStaticTv}}{{{f(best['tv_pct'])}}}")
        L.append(f"\\newcommand{{\\RateBestStaticUpd}}{{{f(best['upd_pct'])}}}")
        L.append(f"\\newcommand{{\\RateBestStaticE}}{{{f(best['combined_kwh_day'])}}}")
        res["best_static"] = best

    try:
        plot_rate_sweep(groups, rbc_sf, OUT)
    except Exception as e:  # figure is optional
        print("figure skipped:", e)

    # ---------------- C: baselines at epoch 50 ----------------
    for algo, nm in (("iql_flat", "IqlFlat"), ("bc_flat", "BcFlat"), ("bc_sdar", "BcSdar")):
        a50 = mean_runs(pick(rf"^{algo}_t1_e50_sample_s\d+$"))[0]
        a100 = mean_runs(pick(rf"^{algo}_t1_e100_sample_s\d+$"))[0]
        res["baselines_e50"][algo] = {"e50": a50, "e100": a100}
        for k, tg, nd in (("combined_kwh_day", "E", 1), ("tv_pct", "Tv", 1)):
            L.append(f"\\newcommand{{\\Base{nm}EpFifty{tg}}}{{{f((a50 or {}).get(k), nd)}}}")

    (OUT / "numbers_batch5.tex").write_text("\n".join(L) + "\n")
    (OUT / "batch5_summary.json").write_text(json.dumps(res, indent=2, default=float))

    print("== weather ==")
    for tag, w in res["weather"].items():
        for who in ("rbc", "ours"):
            a = w[who] or {}
            print(f"{tag:10s} {who:5s} n={a.get('n', 0):2d} " + " ".join(f"{k}={a.get(k, float('nan')):.2f}" for k, _ in COLS))
        if w["paired_ours_minus_rbc"]:
            print("           ours-rbc", {k: [round(x, 2) for x in v] for k, v in w["paired_ours_minus_rbc"].items()})
        if w.get("rbc_band22_25"):
            a = w["rbc_band22_25"]
            print(f"{tag:10s} rbcB  n={a['n']:2d} " + " ".join(f"{k}={a.get(k, float('nan')):.2f}" for k, _ in COLS))
        if w.get("paired_ours_minus_rbc_band22_25"):
            print("           ours-rbcB", {k: [round(x, 2) for x in v] for k, v in w["paired_ours_minus_rbc_band22_25"].items()})
        for ts, a in (w.get("training_seeds") or {}).items():
            if a:
                print(f"           training seed {ts}: {a['combined_kwh_day']:.1f} kWh/d, {a['tv_pct']:.2f}%")
    if "rbc_sf_reproduction" in res:
        print("RBC SF reproduction (new, reference):", {k: [round(x, 3) for x in v] for k, v in res["rbc_sf_reproduction"].items()})
    print("== update-rate sweep ==")
    for k, a in groups.items():
        if a:
            print(f"{k:18s} n={a['n']} " + " ".join(f"{c}={a[c]:.2f}" for c, _ in COLS))
    print("== baselines e50 vs e100 ==")
    for algo, v in res["baselines_e50"].items():
        print(algo, {e: (round(a["combined_kwh_day"], 1), round(a["tv_pct"], 1)) if a else None for e, a in v.items()})



def plot_rate_sweep(groups, rbc, out):
    """Trade-off view: thermal violations against electricity for the state-independent
    selectors (1x/2x/4x the learned per-subsystem rates, connected; RBC rates open markers),
    always-update, the behaviour controller and the learned selector. Update rates are
    written next to the markers. The shaded quadrant is worse than the learned selector
    on both axes."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    plt.rcParams.update({"font.size": 7, "font.family": "serif", "pdf.fonttype": 42, "ps.fonttype": 42,
                         "axes.linewidth": 0.6, "axes.edgecolor": "#55554f",
                         "xtick.color": "#55554f", "ytick.color": "#55554f"})
    ink, cols = "#1f1f1c", {"periodic": "#2a78d6", "constant": "#1baf7a"}
    names = {"periodic": "Periodic", "constant": "Random"}
    fig, ax = plt.subplots(figsize=(3.4, 2.0))
    L = groups.get("learned")
    if L:
        ax.fill_between([L["combined_kwh_day"], 420], L["tv_pct"], 30, color="#efeee9", lw=0, zorder=0)
    lab_off = {"periodic": (0, 5), "constant": None}   # rates are ~equal for both; label once
    for sel, mk in (("periodic", "s"), ("constant", "^")):
        gs = [(lab, groups.get(f"{sel}_{lab}")) for lab in ("x1", "x2", "x4")]
        gs = [(lab, g) for lab, g in gs if g]
        if gs:
            ax.plot([g["combined_kwh_day"] for _, g in gs], [g["tv_pct"] for _, g in gs], marker=mk,
                    color=cols[sel], lw=1.2, ms=4, label=f"{names[sel]} (1, 2, 4$\\times$ rate)", zorder=3)
            for lab, g in gs:
                if lab_off[sel] is None:
                    continue
                off = (4, 2) if lab == "x1" else lab_off[sel]
                ax.annotate(f"{g['upd_pct']:.0f}% upd.", (g["combined_kwh_day"], g["tv_pct"]),
                            xytext=off, textcoords="offset points", fontsize=5, color="#55554f",
                            ha="left" if lab == "x1" else "center", va="bottom")
        g = groups.get(f"{sel}_rbcrate")
        if g:
            ax.plot(g["combined_kwh_day"], g["tv_pct"], marker=mk, mfc="white", mec=cols[sel], mew=1.0, ms=4.5,
                    ls="none", label=f"{names[sel]} (RBC rate)", zorder=3)
    if groups.get("clock"):
        a = groups["clock"]
        ax.plot(a["combined_kwh_day"], a["tv_pct"], "P", color="#8e44ad", ms=5, label="Time of day (1$\\times$ rate)", zorder=3)
    if groups.get("always"):
        a = groups["always"]
        ax.plot(a["combined_kwh_day"], a["tv_pct"], "o", color="#8a897f", ms=4, label="Always update", zorder=3)
        ax.annotate("100% upd.", (a["combined_kwh_day"], a["tv_pct"]), xytext=(0, -5), textcoords="offset points",
                    fontsize=5, color="#55554f", ha="center", va="top")
    if rbc:
        ax.plot(rbc["combined_kwh_day"], rbc["tv_pct"], "D", color="#eb6834", ms=4, label="Behaviour RBC", zorder=3)
    if L:
        ax.plot(L["combined_kwh_day"], L["tv_pct"], "*", color=ink, ms=10, label="Learned (ours)", zorder=4)
        ax.annotate(f"{L['upd_pct']:.0f}% upd.", (L["combined_kwh_day"], L["tv_pct"]), xytext=(-6, 0),
                    textcoords="offset points", fontsize=5, color=ink, ha="right", va="center")
    ax.set_xlim(288, 420)
    ax.set_ylim(4, 26)
    ax.set_xlabel("Electricity (kWh/day)")
    ax.set_ylabel("Thermal violations (%)")
    ax.grid(alpha=0.25, lw=0.5)
    ax.spines[["top", "right"]].set_visible(False)
    h, l = ax.get_legend_handles_labels()
    want = ["Learned (ours)", "Periodic (1, 2, 4$\\times$ rate)", "Random (1, 2, 4$\\times$ rate)",
            "Time of day (1$\\times$ rate)", "Always update", "Periodic (RBC rate)", "Random (RBC rate)", "Behaviour RBC"]
    order = [l.index(x) for x in want if x in l] + [i for i, x in enumerate(l) if x not in want]
    fig.legend([h[i] for i in order], [l[i] for i in order], loc="lower center", ncol=3, fontsize=5.3,
               frameon=False, bbox_to_anchor=(0.5, 0.0), handletextpad=0.3, columnspacing=0.8,
               labelspacing=0.3)
    fig.tight_layout(rect=(0, 0.16, 1, 1))
    fig.savefig(out / "fig_rate_sweep.pdf", bbox_inches="tight")
    fig.savefig(out / "fig_rate_sweep.png", dpi=220, bbox_inches="tight")


if __name__ == "__main__" and len(sys.argv) == 3 and sys.argv[1] == "--figure-only":
    _r = json.loads(Path(sys.argv[2]).read_text())
    plot_rate_sweep(_r["rates"], _r["weather"]["sf"]["rbc"], Path(sys.argv[2]).parent)
    sys.exit(0)

if __name__ == "__main__":
    main()
